package commands

import (
	"testing"

	"github.com/danieladler/tin/internal/model"
	"github.com/danieladler/tin/internal/storage"
)

func TestCommit_Success(t *testing.T) {
	tmpDir, cleanup := setupTestRepo(t)
	defer cleanup()

	repo, _ := storage.Open(tmpDir)

	// Create and stage a thread
	thread := model.NewThread("claude-code", "", "", "")
	thread.AddMessage(model.NewMessage(model.RoleHuman, "Hello", "", nil))
	repo.SaveThread(thread)
	repo.StageThread(thread.ID, len(thread.Messages))

	// Commit
	err := Commit([]string{"-m", "Test commit"})
	if err != nil {
		t.Fatalf("Commit failed: %v", err)
	}

	// Verify commit was created
	commit, err := repo.GetHeadCommit()
	if err != nil {
		t.Fatalf("GetHeadCommit failed: %v", err)
	}
	if commit == nil {
		t.Fatal("expected commit to be created")
	}
	if commit.Message != "Test commit" {
		t.Errorf("expected message 'Test commit', got %s", commit.Message)
	}

	// Verify index was cleared
	staged, _ := repo.GetStagedThreads()
	if len(staged) != 0 {
		t.Errorf("expected 0 staged threads after commit, got %d", len(staged))
	}
}

func TestCommit_AutoGeneratedMessage(t *testing.T) {
	tmpDir, cleanup := setupTestRepo(t)
	defer cleanup()

	repo, _ := storage.Open(tmpDir)

	// Create and stage a thread
	thread := model.NewThread("claude-code", "", "", "")
	thread.AddMessage(model.NewMessage(model.RoleHuman, "Hello", "", nil))
	repo.SaveThread(thread)
	repo.StageThread(thread.ID, len(thread.Messages))

	// Commit without message should auto-generate from first human message
	err := Commit([]string{})
	if err != nil {
		t.Fatalf("Commit failed: %v", err)
	}

	commit, _ := repo.GetHeadCommit()
	if commit.Message != "Hello" {
		t.Errorf("expected auto-generated message 'Hello', got %s", commit.Message)
	}
}

func TestCommit_NothingStaged(t *testing.T) {
	_, cleanup := setupTestRepo(t)
	defer cleanup()

	// Commit with nothing staged should fail
	err := Commit([]string{"-m", "Empty commit"})
	if err == nil {
		t.Error("expected error when nothing is staged")
	}
}

func TestCommit_MultipleThreads(t *testing.T) {
	tmpDir, cleanup := setupTestRepo(t)
	defer cleanup()

	repo, _ := storage.Open(tmpDir)

	// Create and stage multiple threads
	for i := 0; i < 3; i++ {
		thread := model.NewThread("claude-code", "", "", "")
		thread.AddMessage(model.NewMessage(model.RoleHuman, "Hello", "", nil))
		repo.SaveThread(thread)
		repo.StageThread(thread.ID, len(thread.Messages))
	}

	// Commit
	err := Commit([]string{"-m", "Multiple threads"})
	if err != nil {
		t.Fatalf("Commit failed: %v", err)
	}

	// Verify commit has all threads
	commit, _ := repo.GetHeadCommit()
	if len(commit.Threads) != 3 {
		t.Errorf("expected 3 threads in commit, got %d", len(commit.Threads))
	}
}

func TestCommit_ChainedCommits(t *testing.T) {
	tmpDir, cleanup := setupTestRepo(t)
	defer cleanup()

	repo, _ := storage.Open(tmpDir)

	// Create first commit
	thread1 := model.NewThread("claude-code", "", "", "")
	thread1.AddMessage(model.NewMessage(model.RoleHuman, "First", "", nil))
	repo.SaveThread(thread1)
	repo.StageThread(thread1.ID, len(thread1.Messages))
	Commit([]string{"-m", "First commit"})

	firstCommit, _ := repo.GetHeadCommit()

	// Create second commit
	thread2 := model.NewThread("claude-code", "", "", "")
	thread2.AddMessage(model.NewMessage(model.RoleHuman, "Second", "", nil))
	repo.SaveThread(thread2)
	repo.StageThread(thread2.ID, len(thread2.Messages))
	Commit([]string{"-m", "Second commit"})

	secondCommit, _ := repo.GetHeadCommit()

	// Verify parent relationship
	if secondCommit.ParentCommitID != firstCommit.ID {
		t.Error("second commit should have first commit as parent")
	}
}

func TestCommit_HelpFlag(t *testing.T) {
	_, cleanup := setupTestRepo(t)
	defer cleanup()

	err := Commit([]string{"--help"})
	if err != nil {
		t.Errorf("Commit --help should not error: %v", err)
	}
}

func TestCommit_LongMessageFlag(t *testing.T) {
	tmpDir, cleanup := setupTestRepo(t)
	defer cleanup()

	repo, _ := storage.Open(tmpDir)

	// Create and stage a thread
	thread := model.NewThread("claude-code", "", "", "")
	thread.AddMessage(model.NewMessage(model.RoleHuman, "Hello", "", nil))
	repo.SaveThread(thread)
	repo.StageThread(thread.ID, len(thread.Messages))

	// Commit with --message flag
	err := Commit([]string{"--message", "Using long flag"})
	if err != nil {
		t.Fatalf("Commit with --message failed: %v", err)
	}

	commit, _ := repo.GetHeadCommit()
	if commit.Message != "Using long flag" {
		t.Errorf("expected message 'Using long flag', got %s", commit.Message)
	}
}
